### ISSUE TITLE
controller input not working

### ISSUE THREAD

**Issue by Guaxinobers** [Waterdish/Shipwright-Android#17]
i've got a generic controller that works fine on other apps, it gets recognized fine by them, however not here, i cant open the menu and none of the inputs are working in game, dk if it is me being dumb, a bug on my end or just my controller that suck ass and isnt compatible at all (most probable).
thx

**Comment by Guaxinobers** [comment]
so i tested it with an older device i have and it worked fine, i guess is the phone i'm using? idk

**Comment by Waterdish** [comment]
That's really weird. Thanks for letting me know. I wonder what would cause that

**Comment by Lulzigi** [comment]
Actually, I've got a similar problem. I connected a Switch Pro Controller. The minus button brings up the menu properly and when trying to bind the controller is recognized, the sticks even display movement in the controller mapping menu, but I can't progress beyond the title screen. I also tried rebinding the start and a buttons (which it recognized and let me do) but still no response from the actual game.

**Comment by EgoBizarro** [comment]
My Razer Kishi is also not recognized at all, not even pressing select doesn't anything. Aren't xinput controllers supported? Because I think the Kishi is basically just one of those.

**Comment by Lulzigi** [comment]
Okay, I think I figured it out and it's probably the same problem for all of us. Controller inputs aren't recognized by the game if the SoH enhancements menu is active. This is likely intended behavior so the controller can be used to navigate said menu on the phone screen. This isn't default behavior in PC SoH, but it kinda makes sense here because the menu is so tiny on a phone screen. Once I closed the SoH menu with the - button, my inputs were recognized by the game proper. I still can't map all my inputs because the c-buttons aren't visible in the controller configuration window though.

**Comment by EgoBizarro** [comment]
For me it's right from the start, I don't have the enhancements menu open, I can't even open it.

**Comment by Waterdish** [comment]
For the people that it's not working at all, what type of phone do you have?

**Comment by EgoBizarro** [comment]
Poco X3 NFC. The Kishi works fine with it normally.

**Comment by NotTeb** [comment]
I have the same issue, though it could just be my phone as I have a pretty bad Motorola g10

**Comment by Guaxinobers** [comment]
> For the people that it's not working at all, what type of phone do you have?

A xiaomi note 7, the other one is a pretty old one, cant even remember the model

**Comment by handiman0** [comment]
doesnt work on nvida shield with multi controleres

**Comment by Horonelius** [comment]
I have occasionally had this happen on the Retroid 3+, but it only affects the joysticks, and putting quickly turning the screen off and on again fixes it. Could be a Retroid thing as well and unrelated to SoH.

**Comment by CesarGZM** [comment]
The only solution I found to be able to play with a generic control was to open the game on PC, once opened press F1 to open the improvements menu and open a window such as the control configuration and close the game, then you will copy the file "shipofharkinian.json" to the "Android\data\com.dishii.soh\files" folder, when I did this and opened the game the menu already appeared open and with the touchscreen I configured the control.
Unfortunately if I close the menu I am unable to reopen it because pressing "-" does not open it with this control

**Comment by CesarGZM** [comment]
The only solution I found to be able to play with a generic control was to open the game on PC, once opened press F1 to open the enhancements menu and open a window such as the control configuration and close the game, then you will copy the file "shipofharkinian.json" to the "Android\data\com.dishii.soh\files" folder, when I did this and opened the game the menu already appeared open and with the touchscreen I configured the control.
Unfortunately if I close the menu I am unable to reopen it because pressing "-" does not open it with this control

**Comment by Waterdish** [comment]
Thank you that will be useful information to track down the issue.

**Comment by EgoBizarro** [comment]
No news on this? Would be a pity not to be able to play this because the port seems to work fine otherwise.

**Comment by Waterdish** [comment]
Yeah no update yet, sorry. Haven't had much time to look into it.

**Comment by EgoBizarro** [comment]
No problem, take your time. Just hoping you're not giving up on it :>

**Comment by Waterdish** [comment]
Could somebody let me know if the new instructions in the readme allow you to get your controller detected? You can now open the enhancements menu without a controller.

**Comment by EgoBizarro** [comment]
YES, that works! Back-button opens menu and under controller I can select the Razer Kishi and map the buttons.
Only that window is cut off for me on the sides (so I can't see what buttons I'm mapping on the left side) and there's no making that window bigger while there is in some other windows for some reason. But I figured the mappings out and it's working fine. Still looking for the C-Buttons and stuff, but I'm probably just looking in the wrong places or something. Will test further. Controller generally working now, though, so that's great, good job!

**Comment by Waterdish** [comment]
Settings -> Graphics -> ImGui Menu Scale. If you set that smaller, you should be able to see the C button mapping.

**Comment by EgoBizarro** [comment]
Yeah, I found it, thanks :)
